### ISSUE TITLE
Replacing the insecure link for "Python For You And Me"

### ISSUE THREAD

**Issue by moizsajid** [dgplug/lektorweb#1]
I wanted to replace the link for the "Python For You And Me" from [https://pymbook.rtfd.org/](https://pymbook.rtfd.org/) to [http://pymbook.readthedocs.io/en/latest/](http://pymbook.readthedocs.io/en/latest/) because the current link is not secure. I browsed through the repo to the find the section where I can make this change; however, I could not find the section for "Python For You And Me". Can anyone please help me out? Thank you!

**Comment by kushaldas** [comment]
Thanks for the issue, it has been fixed.
